{% set name = "dbfread" %}
{% set version = "2.0.7" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "07c8a9af06ffad3f6f03e8fe91ad7d2733e31a26d2b72c4dd4cfbae07ee3b73d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - dbfread

about:
  home: https://dbfread.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'read data from dbf files'
  dev_url: https://github.com/olemb/dbfread
  doc_url: https://dbfread.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
