travis:
  secure:
    BINSTAR_TOKEN: I4RJlhPVAs1YfW0f8lG51zhRdouMbSBltYbCAvOj9gX1Kj+PxDt5nJmzjZUaaBQ0WcVxfGa+kvjt0El90I45w534JTpueFv8CpoWob0nUoCrlnlolxUdx+6ZTPKr+hFSs1p/dGaDSUpPBt6cJkU5Ed+15FFXyTevfdUbS6NKt6jOePIYpzSTXIjXfR5JLxMV3pXy+g0h9KIg3oACVdWROGPQYrOQ9WarUc4dHjIk335wLWTurmPllnSeIFErhTAUMprL9jgcB2GI9+BQxnO1fBDoNAPlqOke/CNvF8wiWtnCPgS88Y7IhXC3YcpXiWBh/VRVMzA3viwafjQESwtKomrnrFwKZF1RC7bSJrsWDqXBAC7u+mHwzLoBnJ/3uMWQjyf2co9+B1beE1/Y5WltpbaQXvOyP2fsqbOiDC9Idzo9zDIaFfQBGtuPMondPmOW3/ivxYzygQ7Hbq7pGd0PhjHULB65jQzlhhBEIfJe5dg8Xdk3lQYpy4EOIBmzVbs/HaYnDxE7A3Bqd6xNt/WwMHm9Q85j1SSUJTuB7OZ/MOuqYKKr8nNlqBcC2dHvyGB1s6weX7w6ZsypoR6z+NGEUcACsdMDZNovsco0JVn2DVKSNu5oVSZnJHes6nz/pgh7t6ckyAnhlXHrH8hMvtt06lJw9jmwCtYTDTOMG2dRLd8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
